<a href="https://colab.research.google.com/github/zerostone-kim/ml.yah.ac/blob/master/tensorflow_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
# 데이터를 준비하자
import pandas as pd
import tensorflow as tf


In [19]:
# 데이터를 불러오자

파일경로 =  'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

#원핫인코딩을 위한 코드추가
아이리스 = pd.get_dummies(아이리스)

In [22]:
# 독립변수와 종속번수
print(아이리스.head())

독립 = 아이리스[['꽃잎길이','꽃잎폭','꽃받침길이','꽃받침폭']]
종속 = 아이리스[['품종_setosa','품종_versicolor','품종_virginica']]


   꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0


In [23]:
# 모델의 구조를 만들자
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
                          
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')


In [24]:
# 학습 시키자
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1690 - accuracy: 0.9533
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1683 - accuracy: 0.9600
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1687 - accuracy: 0.9667
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1680 - accuracy: 0.9600
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1684 - accuracy: 0.9600
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1678 - accuracy: 0.9600
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1681 - accuracy: 0.9667
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1680 - accuracy: 0.9667
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1677 - accuracy: 0.9600
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1677 - accuracy: 0.9600


In [27]:
# 예측해보자
print(model.predict(독립[:5]))

print(종속[:5])

[[9.9889439e-01 1.1054638e-03 1.2241223e-07]
 [9.9566263e-01 4.3360810e-03 1.3464261e-06]
 [9.9801219e-01 1.9874130e-03 3.9890395e-07]
 [9.9457502e-01 5.4233894e-03 1.5214259e-06]
 [9.9910742e-01 8.9241256e-04 8.1885027e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [28]:
model.get_weights()

[array([[ 0.1895346 , -0.23678091, -0.3670378 ],
        [ 2.930098  ,  0.36073133, -1.6493843 ],
        [-3.547478  , -0.00863935,  0.5951469 ],
        [-3.9609783 , -2.0770092 ,  2.0008323 ]], dtype=float32),
 array([ 2.1993084,  1.2287499, -1.8407865], dtype=float32)]