<a href="https://colab.research.google.com/github/zerostone-kim/ml.yah.ac/blob/master/tensorflow_iris_HL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 데이터를 준비하자
import pandas as pd
import tensorflow as tf


In [3]:
# 데이터를 불러오자

파일경로 =  'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

#원핫인코딩을 위한 코드추가
아이리스 = pd.get_dummies(아이리스)

In [4]:
# 독립변수와 종속번수
print(아이리스.head())

독립 = 아이리스[['꽃잎길이','꽃잎폭','꽃받침길이','꽃받침폭']]
종속 = 아이리스[['품종_setosa','품종_versicolor','품종_virginica']]


   꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0


In [5]:
# 모델의 구조를 만들자
X = tf.keras.layers.Input(shape=[4])

# hidden layer 추가
H = tf.keras.layers.Dense(4, activation='swish')(X)

Y = tf.keras.layers.Dense(3, activation='softmax')(H)
                          
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')


In [6]:
# 학습 시키자
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0629 - accuracy: 0.9867
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0633 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0629 - accuracy: 0.9867
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0619 - accuracy: 0.9867
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0636 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0615 - accuracy: 0.9867
Epoch 7/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0625 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0629 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0643 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0617 - accuracy: 0.9867


In [7]:
# 예측해보자
print(model.predict(독립[:5]))

print(종속[:5])

[[9.9902976e-01 9.1953337e-04 5.0681254e-05]
 [9.9802053e-01 1.9117082e-03 6.7759807e-05]
 [9.9899083e-01 9.6146751e-04 4.7621132e-05]
 [9.9839312e-01 1.5532665e-03 5.3559106e-05]
 [9.9917406e-01 7.7923760e-04 4.6679583e-05]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [8]:
model.get_weights()

[array([[ 0.40622768, -0.04999721, -0.2824079 , -0.6935629 ],
        [-1.0547166 , -0.5887844 ,  0.2706064 , -0.5175176 ],
        [ 1.2785794 ,  0.6505694 , -0.42172727,  1.2230871 ],
        [ 0.7120732 ,  0.37302554,  0.16927682,  1.1777883 ]],
       dtype=float32),
 array([-0.232947 , -0.599976 ,  0.2021138, -0.673043 ], dtype=float32),
 array([[-2.8612819 ,  0.27507645, -0.64530206],
        [-3.8296869 ,  0.17081134,  1.736896  ],
        [-4.5450196 ,  1.9001039 ,  3.6920364 ],
        [-3.8218307 , -2.5941708 ,  2.912188  ]], dtype=float32),
 array([ 4.3515434 , -0.06841998, -1.7146683 ], dtype=float32)]